### PR TITLE
Add missing writeTMVar to MonadSTM

### LINKED ISSUE #152: Add `writeTMVar` to `MonadSTM`
`writeTMVar` was added in `stm-2.5.1.0`, but it's not yet included in `MonadSTM`

### PR DESCRIPTION
**Pull request by nitinprakash96**
Should close #152

### CODE REVIEW

**Comment by bolt12** [comment]
Thanks! Please make sure to update the Changelog as well!

**Comment by nitinprakash96** [comment]
This is also going to need `MIN_VERSION` macros since writeTMVar was introduced in 2.5.1
Good thing CI caught that.

**Comment by bolt12** [comment]
Changelog for io-sim is missing 😄

**Review by bolt12 — APPROVED** [review]
LGTM Thanks!!

**Pull request merged**
