### PR TITLE
Use IntPSQ instead of OrdPSQ for `timers` map.

### PR DESCRIPTION
**Pull request by Saizan**
Using `IntPSQ` is much faster (20x) on some larger loads, and is recommended by `psqueues` where possible.

### CODE REVIEW

**Comment by bolt12** [comment]
Great! Could you make the changes for IOSimPOR too?

**Comment by Saizan** [comment]
@bolt12 sure! Btw, is there something we could use to benchmark the `runqueue` field? We likely want to change that to `HashPSQ`.

**Comment by bolt12** [comment]
> @bolt12 sure! Btw, is there something we could use to benchmark the `runqueue` field? We likely want to change that to `HashPSQ`.

I guess you can use https://github.com/IntersectMBO/ouroboros-network/blob/main/ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Testnet.hs#L121

**Comment by Saizan** [comment]
The tests performance seem unaffected by the changes, probably not enough threads to make it relevant, but should likely help otherwise.

Also I had to add an orphan `Hashable (Down a)` instance, let me know if you'd prefer it to be moved or if you have other comments about coding style.

**Review by bolt12 — APPROVED** [review]
LGTM! Thank you !!

**Pull request merged**
